apiVersion: v1
kind: Service
metadata:
  name: heart-disease-service
  labels:
    app.kubernetes.io/name: heart-disease-api
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: heart-disease-prediction
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: heart-disease-api-2024ab05112
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: heart-disease-api
    app.kubernetes.io/component: backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30007
