apiVersion: v1
kind: Service
metadata:
  name: heart-disease-service
  labels:
    app.kubernetes.io/name: heart-disease-api
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: heart-disease-prediction
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: heart-disease-api
    app.kubernetes.io/component: backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30007
