apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: heart-disease-unified-ingress
  labels:
    app.kubernetes.io/name: unified-gateway
    app.kubernetes.io/part-of: heart-disease-prediction
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: heart-disease-2024ab05112.centralindia.cloudapp.azure.com
    http:
      paths:
      # Simple Catch-All. Everything goes to Django Frontend.
      # Django will then Reverse Proxy /api, /grafana, etc. internally.
      - path: /
        pathType: Prefix
        backend:
          service:
            name: heart-disease-frontend-service
            port:
              number: 30008
