apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-frontend
  labels:
    app.kubernetes.io/name: frontend-gateway
    app.kubernetes.io/part-of: heart-disease-prediction
spec:
  ingressClassName: nginx
  rules:
  - host: heart-disease-2024ab05112.centralindia.cloudapp.azure.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: heart-disease-frontend-service
            port:
              number: 30008
