apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: heart-disease-unified-ingress
  labels:
    app.kubernetes.io/name: unified-gateway
    app.kubernetes.io/part-of: heart-disease-prediction
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: heart-disease-2024ab05112.centralindia.cloudapp.azure.com
    http:
      paths:
      # 1. API - Matches /api or /api/...
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: heart-disease-service
            port:
              number: 80
      # 2. Grafana - Matches /grafana or /grafana/...
      - path: /grafana(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: grafana
            port:
              number: 3000
      # 3. Prometheus - Matches /prometheus or /prometheus/...
      - path: /prometheus(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: prometheus-service
            port:
              number: 9090
      # 4. Frontend - Catch-All regex
      - path: /()(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: heart-disease-frontend-service
            port:
              number: 30008
